services:
  - type: web
    name: django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn healthy_body.wsgi:application"
    envVars:
      - key: DEBUG
        value: False