# Generated by Django 5.1.3 on 2026-04-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("bmi_status", models.CharField(max_length=20)),
                ("budget", models.IntegerField()),
                ("food_type", models.CharField(max_length=10)),
                ("plan_text", models.TextField()),
                ("last_reply", models.CharField(default="YES", max_length=10)),
            ],
        ),
    ]
