# Generated by Django 6.0.1 on 2026-04-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmirecord',
            name='user',
        ),
    ]
