# Generated by Django 5.1.3 on 2026-04-24 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("date", models.DateField(auto_now_add=True)),
                ("followed", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="aiplan",
            name="last_reply",
        ),
        migrations.AddField(
            model_name="aiplan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aiplan",
            name="food_type",
            field=models.CharField(max_length=20),
        ),
    ]
