# Generated by Django 5.1.3 on 2026-04-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "healthy",
            "0002_dailylog_remove_aiplan_last_reply_aiplan_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiplan",
            name="food_type",
            field=models.CharField(max_length=10),
        ),
    ]
