# Generated by Django 5.1.3 on 2026-04-24 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthy", "0003_alter_aiplan_food_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bmi", models.FloatField()),
                ("category", models.CharField(max_length=20)),
                ("budget", models.IntegerField(blank=True, null=True)),
                ("food_type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AIPlan",
        ),
        migrations.DeleteModel(
            name="DailyLog",
        ),
    ]
