# Generated by Django 6.0.1 on 2026-04-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0007_bmirecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('diet_reply', models.TextField()),
                ('exercise_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
