# Generated by Django 6.0.1 on 2026-04-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0009_remove_userhealthplan_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdietplan',
            name='body_goal',
            field=models.CharField(default='General Fitness', max_length=50),
        ),
    ]
